package com.rudraksha.shopsphere.shared.models.enums;

public enum EventType {
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    ORDER_PLACED,
    ORDER_CONFIRMED,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    ORDER_CANCELLED,
    PAYMENT_INITIATED,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    INVENTORY_UPDATED
}
